### ISSUE TITLE
Example using react-dropzone

### ISSUE THREAD

**Issue by rodrigovidal** [quarklemotion/html5-file-selector#1]
Hi, could you please provide an example of this with react-dropzone? I've been trying but no luck so far.

Thanks.

**Comment by quarklemotion** [comment]
Hi @rodrigovidal, sorry just seeing this issue - the best example for integrating with react-dropzone is this open pull request: https://github.com/react-dropzone/react-dropzone/pull/594
I'm hoping this gets merged into react-dropzone soon!

**Comment by rodrigovidal** [comment]
@quarklemotion no problem :) I managed to use it a couple of months ago. Thank you for your work on it 👍
